### PR TITLE
Fix leaky primary view docking, fixes #973

### LINKED ISSUE #973: App primary view instances receive onDock/onUndock calls beyond the app instance's lifecycle
In the case of a unit/integration test suite which repeatedly starts and stops app instances within the same process, the app's primary view instance leaks, and continues to receive `onDock()`/`onUndock()` calls even after its stage has been hidden and its app has received a `stop()` call from the test framework.

### PR DESCRIPTION
**Pull request by carltonwhitehead**

### CODE REVIEW

**Comment by carltonwhitehead** [comment]
Disappointed to see the CI checks failed. The test passes locally on two different machines. From the logs, it looks like the second app instance never received its onDock callback. Not sure why there would be a discrepancy between local and CI environments there. I'm out of time right now, but I'll take a closer look tonight.

**Comment by edvin** [comment]
Could it be due to platform differences or JDK differences perhaps?

**Comment by carltonwhitehead** [comment]
Platform different is my first guess. Local machines are KDE neon / Ubuntu 18.04 base, ZuluFX 8.

**Comment by carltonwhitehead** [comment]
Here's the relevant section of logging from running the test on my local machine. Intend to compare against the log from CI to try to see what the difference is.

```
[INFO] Running tornadofx.tests.PrimaryViewLeakTest
registering stage...
setting up application...
Apr 30, 2019 6:01:25 PM tornadofx.FX$Companion importChildInterceptors
INFO: Adding Child Interceptor tornadofx.tests.FirstInterceptor@1f96e1aa
Apr 30, 2019 6:01:25 PM tornadofx.FX$Companion importChildInterceptors
INFO: Adding Child Interceptor tornadofx.tests.SecondInterceptor@60473c9a
PrimaryLeakView.init()
PrimaryLeakView.dockCounter: 1
cleaning up stages...
cleaning up app...
registering stage...
setting up application...
PrimaryLeakView.init()
PrimaryLeakView.dockCounter: 1
cleaning up stages...
cleaning up app...
Asserting on view: 0
Asserting on view: 1
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.737 s - in tornadofx.tests.PrimaryViewLeakTest
```

**Comment by carltonwhitehead** [comment]
Here's the relevant section of log from the CI

```
[[1;34mINFO[m] Running tornadofx.tests.[1mPrimaryViewLeakTest[m
registering stage...
setting up application...
PrimaryLeakView.init()
Apr 30, 2019 10:02:53 PM tornadofx.CssSelectionBlock <init>
WARNING: CSS rule caused an error
kotlin.TypeCastException: null cannot be cast to non-null type javafx.scene.paint.Color
	at tornadofx.PropertyHolder$$special$$inlined$cssprop$1.getValue(CSS.kt:849)
	at tornadofx.PropertyHolder$$special$$inlined$cssprop$1.getValue(CSS.kt:845)
	at tornadofx.PropertyHolder.getBaseColor(CSS.kt)
	at tornadofx.testapps.Styles$1.invoke(StylesheetErrorTest.kt:22)
	at tornadofx.testapps.Styles$1.invoke(StylesheetErrorTest.kt:18)
	at tornadofx.CssSelectionBlock.<init>(CSS.kt:931)
	at tornadofx.CssSelection.<init>(CSS.kt:887)
	at tornadofx.SelectionHolder$DefaultImpls.invoke(CSS.kt:63)
	at tornadofx.Stylesheet.invoke(CSS.kt:96)
	at tornadofx.testapps.Styles.<init>(StylesheetErrorTest.kt:20)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at sun.net.www.protocol.css.Handler$CSSURLConnection.getInputStream(Handler.kt:20)
	at java.net.URL.openStream(URL.java:1045)
	at com.sun.javafx.css.parser.CSSParser.parse(CSSParser.java:244)
	at com.sun.javafx.css.StyleManager.loadStylesheetUnPrivileged(StyleManager.java:1104)
	at com.sun.javafx.css.StyleManager.loadStylesheet(StyleManager.java:935)
	at com.sun.javafx.css.StyleManager.processStylesheets(StyleManager.java:1556)
	at com.sun.javafx.css.StyleManager.gatherSceneStylesheets(StyleManager.java:1625)
	at com.sun.javafx.css.StyleManager.findMatchingStyles(StyleManager.java:1663)
	at javafx.scene.CssStyleHelper.createStyleHelper(CssStyleHelper.java:111)
	at javafx.scene.Node.reapplyCss(Node.java:8985)
	at javafx.scene.Node.impl_reapplyCSS(Node.java:8948)
	at javafx.scene.Scene$11.onChanged(Scene.java:1502)
	at com.sun.javafx.collections.TrackableObservableList.lambda$new$29(TrackableObservableList.java:45)
	at com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:164)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.collections.ModifiableObservableListBase.addAll(ModifiableObservableListBase.java:102)
	at tornadofx.FX$Companion.applyStylesheetsTo(FX.kt:321)
	at tornadofx.App.start(App.kt:92)
	at org.testfx.toolkit.impl.ApplicationServiceImpl.lambda$start$61(ApplicationServiceImpl.java:62)
	at org.testfx.util.WaitForAsyncUtils.callCallableAndSetFuture(WaitForAsyncUtils.java:363)
	at org.testfx.util.WaitForAsyncUtils.lambda$asyncFx$9(WaitForAsyncUtils.java:115)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)

cleaning up stages...
cleaning up app...
registering stage...
setting up application...
PrimaryLeakView.init()
Apr 30, 2019 10:02:53 PM tornadofx.CssSelectionBlock <init>
WARNING: CSS rule caused an error
kotlin.TypeCastException: null cannot be cast to non-null type javafx.scene.paint.Color
	at tornadofx.PropertyHolder$$special$$inlined$cssprop$1.getValue(CSS.kt:849)
	at tornadofx.PropertyHolder$$special$$inlined$cssprop$1.getValue(CSS.kt:845)
	at tornadofx.PropertyHolder.getBaseColor(CSS.kt)
	at tornadofx.testapps.Styles$1.invoke(StylesheetErrorTest.kt:22)
	at tornadofx.testapps.Styles$1.invoke(StylesheetErrorTest.kt:18)
	at tornadofx.CssSelectionBlock.<init>(CSS.kt:931)
	at tornadofx.CssSelection.<init>(CSS.kt:887)
	at tornadofx.SelectionHolder$DefaultImpls.invoke(CSS.kt:63)
	at tornadofx.Stylesheet.invoke(CSS.kt:96)
	at tornadofx.testapps.Styles.<init>(StylesheetErrorTest.kt:20)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at sun.net.www.protocol.css.Handler$CSSURLConnection.getInputStream(Handler.kt:20)
	at java.net.URL.openStream(URL.java:1045)
	at com.sun.javafx.css.parser.CSSParser.parse(CSSParser.java:244)
	at com.sun.javafx.css.StyleManager.loadStylesheetUnPrivileged(StyleManager.java:1104)
	at com.sun.javafx.css.StyleManager.loadStylesheet(StyleManager.java:935)
	at com.sun.javafx.css.StyleManager.processStylesheets(StyleManager.java:1556)
	at com.sun.javafx.css.StyleManager.gatherSceneStylesheets(StyleManager.java:1625)
	at com.sun.javafx.css.StyleManager.findMatchingStyles(StyleManager.java:1663)
	at javafx.scene.CssStyleHelper.createStyleHelper(CssStyleHelper.java:111)
	at javafx.scene.Node.reapplyCss(Node.java:8985)
	at javafx.scene.Node.impl_processCSS(Node.java:9182)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1249)
	at javafx.scene.Node.processCSS(Node.java:9058)
	at javafx.scene.Scene.doCSSPass(Scene.java:545)
	at javafx.scene.Scene.preferredSize(Scene.java:1643)
	at javafx.scene.Scene.impl_preferredSize(Scene.java:1720)
	at javafx.stage.Window$9.invalidated(Window.java:846)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.stage.Window.setShowing(Window.java:922)
	at javafx.stage.Window.show(Window.java:937)
	at javafx.stage.Stage.show(Stage.java:259)
	at tornadofx.App.start(App.kt:101)
	at org.testfx.toolkit.impl.ApplicationServiceImpl.lambda$start$61(ApplicationServiceImpl.java:62)
	at org.testfx.util.WaitForAsyncUtils.callCallableAndSetFuture(WaitForAsyncUtils.java:363)
	at org.testfx.util.WaitForAsyncUtils.lambda$asyncFx$9(WaitForAsyncUtils.java:115)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)

PrimaryLeakView.dockCounter: 1
cleaning up stages...
cleaning up app...
Asserting on view: 0
[[1;31mERROR[m] [1;31mTests [0;1mrun: [0;1m1[m, [1;31mFailures: [0;1;31m1[m, Errors: 0, Skipped: 0, Time elapsed: 0.15 s[1;31m <<< FAILURE![m - in tornadofx.tests.[1mPrimaryViewLeakTest[m
[[1;31mERROR[m] itShouldNotLeakOnDock(tornadofx.tests.PrimaryViewLeakTest)  Time elapsed: 0.15 s  <<< FAILURE!
java.lang.AssertionError: It should dock only once expected:<1> but was:<0>
	at tornadofx.tests.PrimaryViewLeakTest.itShouldNotLeakOnDock(PrimaryViewLeakTest.kt:45)
```

It looks like StylesheetErrorTest is leaking something. Going to check that out now.

**Comment by carltonwhitehead** [comment]
Tests are all passing now. It turns out the issues were all related to test isolation. The new test was passing locally because I was running it individually rather than the whole suite, so isolation issues were not part of the equation. Ready for a code review now.

**Comment by edvin** [comment]
As far as I can tell, this is looking good. We're missing quite a few tests to verify completely though, but I'll do some more manual checks with my apps before we release.

**Pull request merged**
