### PR TITLE
Add tests for builders.

### PR DESCRIPTION
**Pull request by hastebrot**
This adds some initial tests for builders.

- [x] `text()`

### CODE REVIEW

**Comment by hastebrot** [comment]
From the Travis build:

>Xlib:  extension "RANDR" missing on display ":99.0".

This can be ignored.

**Comment by edvin** [comment]
Nice, great work! I'll read up on TestFX so I can start adding tests myself as well :)

**Comment by hastebrot** [comment]
Yeah, TestFX's documentation is somewhat outdated. I started to rewrite it, using the initial pages of Tornodo FX's wiki as stubs (https://github.com/TestFX/TestFX/wiki/Documentation).

**Comment by edvin** [comment]
Cool :) This upcoming week I'm on vacation, but I'll try to sneak in a couple of hours of reading and maybe write some tests.

**Comment by thomasnield** [comment]
I'll probably check it out as well. Please let us know when the documentation is finished.

**Comment by hastebrot** [comment]
@thomasnield: I like idea of docs that can be read in chronological order. Bootstrapping the docs by using the Tornado FX docs as stubs helps a lot. I'll write a short outline in each chapter and use this outline to "unit test" the chapter. The outline will tell what the chapter aims at. I first need to get the bare structure, this can later be "refactored".

**Comment by thomasnield** [comment]
@hastebrot awesome.

**Comment by hastebrot** [comment]
Issue for TestFX documentation here: https://github.com/TestFX/TestFX/issues/138

**Pull request merged**
