### PR TITLE
Added onDock javadoc

### PR DESCRIPTION
**Pull request by PvdBerg1998**
Added javadoc to onDock since I was confused about what it was for.
Description as given by @t-boom .

Recreating this PR because I accidentally removed the original :)

### CODE REVIEW

**Comment by edvin** [comment]
The onDock callbacks are called either when the component becomes the scene root, or when it's root node is attached to another component (using add). Could we reflect that as well in the comment?

**Comment by PvdBerg1998** [comment]
/**
     * Called when a Component when it becomes the Scene root or
     * when it's root node is attached to another Component.
     * @see UIComponent.add
     */

Something like this?

**Comment by edvin** [comment]
That sounds good :)

**Comment by PvdBerg1998** [comment]
So many typo's though

**Pull request merged**
