### PR TITLE
Autocomplete extension for combobox

### PR DESCRIPTION
**Pull request by aymen083**
Pull request for the issue #251 
I added a callaback and i made tests in the ComboBoxTest.kt

For the builder i did get how to do it.

Aymen Nouira

### CODE REVIEW

**Comment by edvin** [comment]
Great, thank you. I'll merge and add the builder. I will also change the use of the Callback. This JavaFX construct just makes it awkward to use in Kotlin, so a function is a much better option to make the interface nicer.

**Comment by edvin** [comment]
You create an observable arraylist which is then thrown away for each filter invocation. I'll change it so it just returns a list, filtered with the Kotlin collections `filter` function instead :)

There is also an issue:

- If you drop the list and it shows a single or even no entries, then you change the selection so it contains multiple entries -> the list area doesn't expand. I wonder if we can make it expand again.

**Comment by edvin** [comment]
I think the parameter to the autocomplete filter should be `comboBox.converter.toString(current)` instead of just `text`.

**Comment by edvin** [comment]
I'll make sure that the data list is updated if the underlying `comboBox.items` property changes.

**Comment by edvin** [comment]
I'm unsure if it's a good idea to change the underlying `comboBox.items` as a result of the filtering. I think users would expect it to be the same instance they passed in, so this could lead to strange bugs. I wonder if we can filter the selection some other way.

**Comment by aymen083** [comment]
I agree with the for the list. It will be more optimized this way.
For the issue the simplest way to solve it is to make a show hide after the combobox.items modifcation. I will see the implementation of the popup if there is a way to force the recalculation.

If we create a separate filtred list we have to modify the popupcontrol to use this new list when available.

Or we can expose the orignal list in a another method.

**Comment by aymen083** [comment]
I made some modification to the implementation of the default filter to not return a new list at evry call using a filtredList only the predicate is updated.
Then the original list can be retrived by the attribute "source" off the filtredList.

And i solved the issue of popup using reflection with a fall to showhide solution.

This is the patch with modification : 
[Rework_of_filtred_list_to_use_FiltredList_and_modify_the_predicate_instead_of_returning_a_.txt](https://github.com/edvin/tornadofx/files/788770/Rework_of_filtred_list_to_use_FiltredList_and_modify_the_predicate_instead_of_returning_a_.txt)

I can make a pull request if you want.

**Comment by aymen083** [comment]
I tried to make the filter not using `combobox.items` but it sems to be complicated and error prone.
To be able to use an other list than `combobox.items` we should reimplement the `com.sun.javafx.scene.control.skin.ComboBoxListViewSkin` using the filtred list instead of `combobox.items` i tried to make it by overriding some methods but i didn't figure how to do it.

With the proposed implementation in the patch of previous comment, using the default filter the user can retrive the original list in the `source` attribute of the filtredList :

Javadoc of FiltredList :
> public final class FilteredList<E> extends TransformationList<E,E>
> Wraps an ObservableList and filters it's content using the provided Predicate. All changes in the ObservableList are propagated immediately to the FilteredList.  

And i the user make modfication in the original list the changes will be propagated to the filtred list. 

What do thing ?

**Comment by edvin** [comment]
I've tried a lot of different approaches myself, and I've reached the same conclusion: This will require a custom Skin to avoid modifications to the source list. I was able to get it working by overriding ComboBoxListViewSkin, but the approach had problems. A complete reimplementation would be best. It's kind of unfortunate, because we'd inherit some maintenance responsibilities for the ComboBox. However, a custom skin could be the gateway to even cooler functionality in the future.

I could try to create a custom skin the coming weekend. If it works, this will be the best approach I think!

**Comment by edvin** [comment]
Let me know when you have time to check the new skin implementation :)

**Pull request merged**
