### PR TITLE
Added initialDirectory to chooseFile

### PR DESCRIPTION
**Pull request by MGlolenstine**
After wanting to do so, I found out that that's not a feature, even tho it is for a chooseDirectory.
Opening a PR for an addition of that feature.

### CODE REVIEW

**Comment by edvin** [comment]
This sounds reasonable, but I seem to remember there was a reason for it not being added. @ruckustboom - do you remember a discussion about this?

**Comment by ruckustboom** [comment]
Sorry for the late reply, but unfortunately I don't have much to offer. I do remember having this discussion before, but for the life of me, I can't remember the details.

**Comment by MGlolenstine** [comment]
I've tested it thoroughly and I haven't noticed any problems with it (so far), so I think that the changes do pass... But keep in mind, that I've only tested it with Arch Linux and KDE Plasma with Dolphin. So if anyone wants to test it with other platforms, feel free to do so.

**Comment by edvin** [comment]
OK, let's give it a go. I don't see any issues with it either :)

**Pull request merged**
