### PR TITLE
Feature/control builders

### PR DESCRIPTION
**Pull request by t-boom**
Added hyperlink, passwordfield, radiobutton, and togglebutton.

### CODE REVIEW

**Comment by edvin** [comment]
Great! Can you add info to the CHANGELOG as well before I merge?

**Comment by t-boom** [comment]
I don't think the information for this was added to the CHANGELOG. I can add it, but how should I word the magic toggle group functionality?

**Comment by edvin** [comment]
No need to mention the magical toggle group thing, we'll mention in in the docs instead :)

**Comment by t-boom** [comment]
Sounds good. I included the changes (along with several others) in [my most recent PR](https://github.com/edvin/tornadofx/pull/82)

**Pull request merged**
