### PR TITLE
Update jdk9 branch to current master

### PR DESCRIPTION
**Pull request by jansorg**
@edvin This updates your jdk9 branch to the current master branch. Let me know if you have an idea for the currently open/unsolved issues listed below.
This compiles and works with the JavaFX application I'm working on (except for the unimplemented issues below, of course)

This is a PR to merge the current master into the jdk9 branch.
Changes:
- Use java.json module to work with Java 9

Unsure:
- Async.kt uses the Platform class now instead of the internal com.sun.glass.ui.Application. IMHO this is ok after looking at the the JDK code , but I'm not expert enough in JavaFX to be sure (internal event thread vs. FX user dispatch thread)

Open issues:
- export of tornadofx.osgi is currently disabled in module-info.java, was required to make the javadoc build step work
- Unsure if sun.net.www.protocol.css should be published in module-info.java
- SmartResize.kt: Resize to fit to content is currently disabled as Java 9 hides the called methods / classes
- ItemControls.kt was using TableRowSkin from the non-public com.sun.* package, it's now using the (newly added?) `javafx.scene.control.skin.TableRowSkinBase` but still has unimplemented methods. Not sure wat the best fix for this is...

### CODE REVIEW

**Comment by edvin** [comment]
Fantastic effort, thank you so much! I will look into this ASAP and get back to you.

**Comment by edvin** [comment]
It looks like the PR was made against master, not my jdk9 branch. Can you create a new against the jdk9 branch so I don't mess with master? :)

**Comment by jansorg** [comment]
@edvin Sorry, I created the PR against the wrong branch. 
I've forked from your JDK9 branch and merged master into that, so this PR should be fine now, I think.
If there's still something wrong with this, let me know...

**Comment by edvin** [comment]
Perfect!

**Pull request merged**
