### PR TITLE
Switch 1.x.x builds to default openjdk8 and install openjfx package

### PR DESCRIPTION
**Pull request by carltonwhitehead**
This PR aims to fix the Travis CI build failing due to Java failing to install. I know it's not great to open a PR for work that isn't complete, but I have to open a PR in order to trigger a build, in order to see if my changes were effective. ~~Please don't rush to merge this until work concludes!~~ Ready for review/merge.

### CODE REVIEW

**Comment by ronsmits** [comment]
how are you certain that this will install the correct openjfx based on the jdk?

**Comment by carltonwhitehead** [comment]
> how are you certain that this will install the correct openjfx based on the jdk?

It installs the system package for openjfx, which is for the default openjdk 8 package on the Ubuntu version. TornadoFX `jdk10` branch-based builds declare openjfx dependencies. I don't think having the old libraries for the older jdk will be an issue. Will re-evaluate if that proves false.

**Comment by carltonwhitehead** [comment]
That makes me wonder... why does the `.travis.yml` on `master` have changes that are only meant for TornadoFX 2.x builds? Shouldn't those Java 11+ concerns be kept separate?

**Comment by carltonwhitehead** [comment]
Looks like the build is passing now. I now consider this PR done and ready for review/merge

**Comment by edvin** [comment]
Thank you, Carlton!

**Pull request merged**
