### PR TITLE
Add Node event handler for long and short presses

### PR DESCRIPTION
**Pull request by bvolkmer**
This is my first working try.

Used in a datagrid like:
```
selectionModel.selectedIndices.addListener(ListChangeListener {
    while (it.next()) {
        if (it.wasRemoved() && it.list.size <= 0) inSelectionMode = false
}})
cellCache {
    stackpane {
        addShortLongPressHandler(Duration(1000.0), true, { event ->
            if (inSelectionMode) {
                val index: Int = this@datagrid.items.indexOf(it)
                if (selectionModel.isSelected(index)) selectionModel.clearSelection(index)
                else selectionModel.select(it)
            } else {
                controller.open(it)
            }
        }, { event ->
            inSelectionMode = true
            val index: Int = this@datagrid.items.indexOf(it)
            if (selectionModel.isSelected(index)) selectionModel.clearSelection(index)
            else selectionModel.select(it)
        })
    }
}
```

Some side effects like canceling when move off the node before releasing are not considered by now.
A global `var inSelectionMode: Boolean` is used for toggling the toolbar.

### CODE REVIEW

**Comment by edvin** [comment]
Thank you. The name is not a good fit for TornadoFX, and I wonder if there should be separate functions like `longPress` and `shortPress`? I have a Surface Pro in order, will investigate more when it arrives :)

**Comment by edvin** [comment]
I finally got my Surface Pro yesterday, and started looking at this. Will get back to you soon.

**Comment by edvin** [comment]
Shouldn't this listen to `TouchEvent.TOUCH_PRESSED` and `TouchEvent.TOUCH_RELEASED` instead of `MouseEvent`?

**Comment by bvolkmer** [comment]
Depends in if you want it to work with your mouse, too. Might be better. I'll test it this evening.

**Comment by edvin** [comment]
Hey! I have taken your code and altered it slightly so you can add either short or long press, or both. This improves the syntax and is more flexible. I guess it is bad form to close your PR and implement it myself with your code so I just want to make sure you get all the credit for this. Nice work!

The API is now:

```kotlin
button("Short or longpress me") {
    longpress { println("Long") }
    shortpress { println("Short") }
}
```
They also support the `consume` parameter, and `longpress` supports `threshold` so you can write:

```kotlin
longpress(1.second, true) { println("Long, consumed after one second") }
```
Thank you for your work on this. This feature will make it into the upcoming 1.7.2 release, which is right around the corner :)

**Comment by bvolkmer** [comment]
As it was quite unfinished at the time of posting, it would have been better put in a gist. But thanks anyway. Its nice to see it in the release so soon.

**Pull request closed without merging**
