### PR TITLE
Add travis configuration file.

### PR DESCRIPTION
**Pull request by hastebrot**
We probably need to add a Travis hook.

### CODE REVIEW

**Comment by hastebrot** [comment]
@edvin Could you please add a hook for Travis (available under Repository > Settings > Webhooks & Services.

>Travis CI is a distributed continuous integration service.
>By enabling this hook, Travis CI will listen to push and pull request events to trigger new builds.

**Comment by edvin** [comment]
OK! Hook added :)

**Comment by hastebrot** [comment]
Yeah, tests are running.

**Comment by hastebrot** [comment]
Hmm.

>[ERROR] /home/travis/build/edvin/tornadofx/src/main/java/tornadofx/Builders.kt: (21, 15) None of the following functions can be called with the arguments supplied: 
>public constructor Tab() defined in javafx.scene.control.Tab
>public constructor Tab(p0: kotlin.String!) defined in javafx.scene.control.Tab

**Comment by edvin** [comment]
Strange, it built locally. I just made that change and actually tested the functionality locally. Let me double check.

**Comment by edvin** [comment]
Travis is running JDK 1.8.0_31, the tab constructor I use was added in _40 :) Is there any way to get a newer JDK in Travis?

**Comment by hastebrot** [comment]
I could download a newer JDK and add it's directory to the cache. Maybe Travis provides a newer JDK version out-of-the-box. Let's see.

**Comment by edvin** [comment]
Still running with 31 it seems. I saw the apt step though.

**Comment by hastebrot** [comment]
We can't use Docker containers for this and need to sudo. The SO answer said, this isn't necessary.

http://stackoverflow.com/questions/32330868/travis-ci-jdk-switcher-to-custom-java-installation/32354225#32354225

**Comment by edvin** [comment]
I've never used Travis before, but it seems it's possible to run the Trusty Beta image by adding this to the build file:

```
sudo: required
dist: trusty
```

That should get us 1.8.0_51 :) Can you try?

**Comment by hastebrot** [comment]
The old error was:

>Disallowing packages: oracle-java8-installer8
>If you require these packages, please review the package approval process at: https://github.com/travis-ci/apt-package-whitelist#package-approval-process

>it's possible to run the Trusty Beta image

Will try this.

**Comment by edvin** [comment]
8u72 - you did it :))

**Comment by hastebrot** [comment]
>Saving to: `jdk-8u72-linux-x64.tar.gz'

I had a typo in the package name (`oracle-java8-installer8` instead `oracle-java8-installer`). I still make some mistakes when using VIM-mode for IntelliJ.

**Comment by edvin** [comment]
Ah, seemed strange that oracle-java8-installer would not already be approved :)

**Comment by hastebrot** [comment]
>[INFO] No tests to run.

What? Hmm...

**Comment by edvin** [comment]
Maybe the surefire-plugin needs to be configured in the pom?

**Comment by hastebrot** [comment]
Oh, I have no idea how to configure this plugin in Maven.

**Comment by edvin** [comment]
I can atleast reproduce the issue locally. I'll look at it, but first I need to sleep :) Will ping you tomorrow :)

**Comment by hastebrot** [comment]
Good night!

**Comment by edvin** [comment]
Good night :)

**Comment by edvin** [comment]
Boom :)

```
Running tornadofx.PropertiesTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.094 sec
```

**Pull request merged**
