### PR TITLE
added textArea property -fx-text-box-border

### PR DESCRIPTION
**Pull request by polmabri**

### CODE REVIEW

**Comment by t-boom** [comment]
This one actually raises an interesting questions. `-fx-text-box-border` is not part of the JavaFX CSS specification, but it is defined in Modena, so **almost** all applications will have it. If the user sets the base style sheet to something else (Caspian for example), this and other such properties may not be defined (not a big deal) or could be defined in a different way (potentially a show-stopper requiring custom properties or forced/raw output).

Should we include such properties and assume everyone will use a stylesheet based of Modena (covering probably >99% of use cases)?

**Comment by edvin** [comment]
Yes, I think it's a good call to include it. Modena is the default, so not including it would mean that it wouldn't be possible to style all facets of Modena without this. Also, as we have seen, the CSS docs are far from complete, so we must assume that people doing advanced styling knows how to check what css classes are applied to a certain node, either by inspecting the source or using scenic view or the layout debugger in TornadoFX. I vote go for it :)

**Comment by bekwam** [comment]
Will there be a default stylesheet change with Java 9 the way there was from FX2 (caspian) -> 8 (modena)?

**Comment by t-boom** [comment]
@bekwam I haven't heard of one. You'd have to ask Jonathan Giles.

**Comment by edvin** [comment]
I'm pretty sure there won't be a modena replacement in JDK9, at least not with the JDK9 release.

**Comment by edvin** [comment]
@t-boom Do you agree about merging this?

**Comment by t-boom** [comment]
Sounds good to me.

We will have to keep this in mind for the future though if a replacement does ever come out. (It'll probably just be a matter of letting the user define their own `PropertyHolder` and creating built in options for the different defaults).

**Comment by edvin** [comment]
Absolutely :) Merged!

**Pull request merged**
