### PR TITLE
Remove non-nullable bound from runAsyncWithProgress

### LINKED ISSUE #1128: runAsyncWithProgress with nullable return type
The `runAsyncWithProgress` function is currently (1.7.19) defined as:

```
fun <T : Any> Node.runAsyncWithProgress(progress: Node, op: () -> T): Task<T>
```

The `Any` bound on `T` prohibits me from using nullable types like `String?`. This is very inconvenient when the operation can have a 'null result' (by being cancelled for example).

I noticed that `runAsync` *does* support nullable values, is there a reason for this difference or is it some kind of oversight? I couldn't find anything in the source code that would cause issues with possibly-null values.

### PR DESCRIPTION
**Pull request by HoldYourWaffle**
Fixes #1128.

I don't have the time to set up a development environment right now so I just edited it in the github UI, meaning there could be very obvious and dumb mistakes/oversights. If tests complain I'll fix it up.

### CODE REVIEW

**Comment by edvin** [comment]
Merged :) Will update 2.0 the same way.

**Comment by HoldYourWaffle** [comment]
This madlad has enough faith in random first-time contributors to merge PR's without waiting for the tests 😮 

Is it possible for me to use this fix right away or do I have to wait until the full 1.17.20 release?

**Comment by edvin** [comment]
Haha, I checked it locally and verified that it wouldn't break any of my projects in addition :) I'll push a new snapshot to oss.sonatype.org right now.

**Comment by edvin** [comment]
Hm.. I got 401 when deploying to nexus. You'd have to pull and build it locally for now I guess. Will investigate tomorrow!

**Comment by HoldYourWaffle** [comment]
I think you [succeeded](https://oss.sonatype.org/service/local/repositories/snapshots/content/no/tornado/tornadofx/1.7.20-SNAPSHOT/tornadofx-1.7.20-20191208.225113-95.pom), it was published a couple of minutes ago and fixes the issue.

By the way, thank you for your immensely quick response & fix! This really was a deal-breaking issue for me, but I was able to get back up and running within half an hour 😄

**Comment by edvin** [comment]
Thanks :) Just remember, if you run into an issue with a function in the framework, you can always submit a PR, or even just fork that function in your own app if you need slightly different behavior. Most functions in TornadoFX are pretty short and easy to fork when needed!

**Pull request merged**
