### PR TITLE
Adding Accordion Support

### PR DESCRIPTION
**Pull request by t-boom**
I'm working on functionality to add Accordions. This is as far as I've got, but I can't think of a clean way to modify the "folds" (such as adding a title, changing the padding, etc.).

### CODE REVIEW

**Comment by t-boom** [comment]
I had another idea where I just added a `Accordion.fold(String?, () -> TitledPane` method, but that would have required adding a bunch of methods to create a node the `TitlePane` content. That may end up being a better way to go.

**Comment by t-boom** [comment]
Here's a demo:

```kotlin
class AccordionTest : View() {
    override val root = StackPane()

    init {
        with(root) {
            prefHeight = 400.0
            prefWidth = 400.0

            accordion {
                folds {
                    textarea { promptText = "Notes" }
                    label("Test 2")
                    label("Test 3")
                }
            }
        }
    }
}
```

accordion-test

**Comment by edvin** [comment]
Thanks for this :)

Some questions :) Why did you call the method `folds`? Is that a name common for accordions? It also seems that you can

**Comment by edvin** [comment]
Forget my question about the function name, folds seems to be a good choice/common name for accordions :)

**Comment by t-boom** [comment]
I can change the name, it just popped into my head and I went with it :)

As far as the fold method goes, I mentioned that in the second comment to this PR. The problem is, `TitledPane` is not a `Pane`, so you would have to create a large number of methods for `TitledPane`. That's not a big deal, but `TitledPane` only takes a single node as content. You can easily do that in your example with something like:

```kotlin
accordion {
    fold("Title here") {
        content = Label("Cool Stuff")
    }
}
```

but then (unless I'm missing something) you can't continue to use the TornadoFX DSL for its content.

**Comment by t-boom** [comment]
(I just started messing around with Kotlin and TornadoFX this week, so I may easily have missed something. Sorry :) )

**Comment by edvin** [comment]
Ah, sorry, it's a bit late here and I'm off my game :)

After you have collected the children into a fake VBox, check if there is only one child, and if so add it as the node for the TitledPane. If there are multiple children in the VBox, just add the vbox as the content node of the TitledPane.

**Comment by edvin** [comment]
```kotlin
accordion {
    fold("Tab 1") {
        label("I will be added as the TitledPane node")
    }
    fold("Tab 2") {
        label("I will be added to the VBox and the VBOx will be the TitledPane node")
        label("Me too!")
    }
}
```

**Comment by edvin** [comment]
The same pattern is used in the `scrollpane` builder:

```kotlin
fun Pane.scrollpane(op: (Pane.() -> Unit)) {
    val vbox = VBox()
    op(vbox)
    val scrollPane = ScrollPane()
    scrollPane.content = if (vbox.children.size == 1) vbox.children[0] else vbox
    this += scrollPane
}
```

**Comment by t-boom** [comment]
I'll do that.

Should I worry about some sort of method to change the pane used? Like an extension property that could be set to `VERTICAL`, `HORIZONTAL`, or `STACKED` (that would resolve to a `VBox`, `HBox`, or `StackedPane` respectively?

I'm not sure how hard that would be to implement, but it popped into my head when I was trying to come up with solutions.

**Comment by edvin** [comment]
That's not really necessary, because if you want an HBox instead, simply do:

 accordion {
    fold("Tab 1") {
        hbox {
            label("Look ma, I'm in an HBox!")
            label("Me too!")
        }
    }
}

**Comment by t-boom** [comment]
Fair point, I didn't think about that :)

**Comment by edvin** [comment]
Sweet! Make the changes and I'll happily accept the PR :)

**Comment by edvin** [comment]
If you want you can also add an entry to the CHANGELOG with reference to this issue.

**Comment by t-boom** [comment]
I've added those changes, but there are still some shortcomings. You can't change any settings of the `TitledPane` without saving it off to a variable (such as padding). Is that acceptable?

**Comment by thomasnield** [comment]
I haven't looked at it since I'm on my phone. But if the TitledPane is returned by the builder, you can always call apply() afterwards to make those manipulations in a block.

**Comment by t-boom** [comment]
(Compulsory example :) )

```kotlin
class AccordionTest : View() {
    override val root = StackPane()

    init {
        with(root) {
            prefHeight = 400.0
            prefWidth = 400.0

            accordion {
                fold("Tab 1") {
                    label("I will be added as the TitledPane node")
                }
                fold("Settings") {
                    label("Name")
                    textfield { promptText = "Enter a name" }
                    label("Name 2")
                    textfield { promptText = "Enter another name" }
                }
            }
        }
    }
}
```

accordion-test-2

**Comment by edvin** [comment]
You could add another parameter that is a function that operates on the TitledPane. This would have to be added before the last op, something like:

```kotlin
fun Accordion.fold(title: String? = null, titledPaneOp: (TitledPane.() -> Unit)? = null, op: (Pane.() -> Unit)) {
    val vbox = VBox()
    op(vbox)
    val fold = TitledPane(title, if (vbox.children.size == 1) vbox.children[0] else vbox).apply {
        titledPaneOp?.invoke(this)
    }
    panes += fold
}
```

It won't be as beautiful when you need it though:

```kotlin
fold("Hello", { padding = Insets.EMPTY }) {
    label("Test")
}
```

EDIT: Just saw @thomasnield 's comment. That might be a better idea, not sure which of the alternatives I like best. What about you guys?

**Comment by edvin** [comment]
Hmm.. I think Thomas is right. If you return the TitledPane from the fold function the code becomes:

```kotlin
fold("Hello") {
    label("Test")
}.apply {
    padding = Insets.EMPTY
}
```

**Comment by t-boom** [comment]
I'm leaning towards Thomas's idea as well. I tried it and it seems to work fine.

**Comment by edvin** [comment]
I gotta get to bed, but if you make that last change and return the TitledPane, I'm sure Thomas can merge this PR for you :))

**Comment by thomasnield** [comment]
Sounds good, let me know when you want me to merge and ill look.

**Comment by t-boom** [comment]
Goodnight :)

@thomasnield Using your approach works great. For example:

```kotlin
fold("Settings") {
    label("Name")
    textfield { promptText = "Enter a name" }
    label("Name 2")
    textfield { promptText = "Enter another name" }
}.apply {
    this@accordion.expandedPane = this
}
```

makes the Settings fold expanded. I'll push it up.

**Comment by t-boom** [comment]
It's pushed. Check it out when you get the change. I'll be off for the night in about 30 min, so if you need more changes after that, they'll have to wait till tomorrow :)

**Comment by thomasnield** [comment]
Merged. Looks good to me. Thanks for putting this together and I'm glad you got involved so quickly!

**Comment by thomasnield** [comment]
I do think it is good practice for control builders to return the control anyway, not just so apply() can be called for specialized cases like this but also to be able to save the controls to variables.

**Comment by edvin** [comment]
Absolutely, I'll make sure they all do right away :) That was the initial intent and almost every builder does that, but I found a couple of stragglers! Good catch, Thomas!

**Pull request merged**
