### PR TITLE
Unit test proving the primary view onDock leak issue, see edvin/tornadofx#973

### PR DESCRIPTION
**Pull request by carltonwhitehead**

### CODE REVIEW

**Comment by carltonwhitehead** [comment]
I'm going to submit a fix for this bug momentarily

**Comment by ruckustboom** [comment]
For future note, you shouldn't close the issue until the PR is accepted/merged, as the issue isn't resolved till then.

**Comment by carltonwhitehead** [comment]
That was my intention. I only closed this PR since I was ready to submit a fix for the issue rather than just a proof of the bug existing.

The issue actually appears to still be open. No harm, no foul I hope?

**Comment by ruckustboom** [comment]
Ah, I see. Sorry, I apparently misunderstood what you were going for. Carry on :)

**Pull request closed without merging**
