### PR TITLE
Tidied up animation chain helpers and added point(x, y)

### PR DESCRIPTION
**Pull request by gbui**
(I wanted to convert `xy` infix calls to `point(x, y)` as I think `x xy y` is a bit hard to read, but I'll wait for your feedback before I do that.)

### CODE REVIEW

**Comment by edvin** [comment]
Yeah, I agree. `xy` was a bit vague. @t-boom What do you think? Maybe I was wrong to insist on `xy`?

**Comment by t-boom** [comment]
I tend to avoid infix functions, so I'd use `point`, but there is a pretty good personal bias there.

@gbui You may also want to add a `point(x: Number, y: Number, z: Number): Point3D` as well, though I'm not sure how often TornadoFX users use the 3D features of JavaFX.

Also, your functions could be written a little more concisely if you want (it's purely a matter of personal taste). For example:

```kotlin
infix fun Animation.and(animation: Animation) = if (this is ParallelTransition) apply {
    children += animation
} else ParallelTransition(this, animation)
```

**Comment by t-boom** [comment]
If you do decide to remove the `xy` infix, I'd recommend deprecating it with a `ReplaceWith("point(x, y")`.

**Comment by edvin** [comment]
Thanks for the feedback @t-boom. We could leave the xy infix function but let the framework use the point function instead. Good idea to add a point(x, y, z) as well!

**Comment by gbui** [comment]
Yes, thank you for the feedback.

In regards to writing the infix functions differently, they _can_ be written shorter. However, I think your suggestion is a little unreadable, at least at first glance. Indeed, there are other ways to shorten the function, but I also think that having similarities between the infix and non-infix functions allows for easier understanding.

**Pull request merged**
