### PR TITLE
Added Paint.asBackground extension

### PR DESCRIPTION
**Pull request by PvdBerg1998**

### CODE REVIEW

**Comment by t-boom** [comment]
I'm not sure if it's worth it to create a new `Paint.kt` file for one extension function. Is there no good place to add it?

**Comment by PvdBerg1998** [comment]
You tell me, haha. I like to add extensions for class X to X.kt. If you know a better destination, let me know, I'll update.

**Comment by t-boom** [comment]
@edvin May have an answer. I believe there is a penalty for each additional file in Kotlin, but I'm not sure how much of an issue it is.

**Comment by t-boom** [comment]
I like the function though. It would be super useful for me.

**Comment by edvin** [comment]
The penalty is basically one extra class, but I agree with @t-boom - we shouldn't add a new file for a single extension function. Maybe we could place it in CSS.kt?

**Comment by edvin** [comment]
Great! It can be moved later without affecting the API so lets not fret about it :) Thanks for this!

**Pull request merged**
