### PR TITLE
Implement SingleAssign functionality

### PR DESCRIPTION
**Pull request by thomasnield**
Please refer to #17.

Let me know if the synchronization `enum` argument name is too long or if you need unit tests.

```kotlin

class MainApp : App() {
    override val primaryView = MainView::class

    class MainView : View() {
        override val root = GridPane()

        var testVar: String by singleAssign()
        // can also be called with argument singleAssign(SingleAssignThreadSafetyMode.SYNCHRONIZED)
        // or singleAssign(SingleAssignThreadSafetyMode.NONE)
        
        init {

            //CASE 1
            println(testVar) //fails correctly

            //CASE 2
            testVar = "Hello"
            println(testVar)
            testVar = "World" //fails correctly

            //CASE 3
            testVar ="Hello"
            println(testVar) //no issues
        }
    }
}
```

### CODE REVIEW

**Comment by thomasnield** [comment]
Shoot, there's conflicts. Let me try to fix that.

**Comment by edvin** [comment]
It would be great with some simple unit tests as well, the framework is already in place, so maybe you can add just a few simple tests?

**Comment by thomasnield** [comment]
Okay fixed conflicts. I'll add the unit tests now.

**Comment by edvin** [comment]
Sweet! You can include a line in the changelog as well if you'd like :)

**Comment by edvin** [comment]
enum name is fine, and in line with what Kotlin does, so it's all good :)

**Comment by edvin** [comment]
We have so much properties goodness now that we might need a new wiki page for this :)

**Comment by thomasnield** [comment]
Done! And yeah we probably do. Let me know if you need help.

**Pull request merged**
