### PR TITLE
Tabpane.creatable bug fix

### PR DESCRIPTION
**Pull request by Warkst**
Found another copy paste bug, Edvin!

### CODE REVIEW

**Comment by edvin** [comment]
Ah, those are the best :)

**Comment by Warkst** [comment]
Any plans on when these changes will be available on maven?

**Comment by edvin** [comment]
There is not enough changes to warrant a release right now, but you can use the snapshots from oss.sonatype.org :)

**Comment by Warkst** [comment]
Cool, thanks!

**Pull request merged**
