### PR TITLE
Deployment using Travis CI

### PR DESCRIPTION
**Pull request by abhinayagarwal**
This PR adds functionality:

* Deploy snapshots to nexus
* Deploy release when tags are pushed and snapshot is removed from version

Once Travis is enabled, the maintainer needs to add the following environment variables:

• NEXUS_USERNAME
• NEXUS_PASSWORD

### CODE REVIEW

**Comment by edvin** [comment]
Thank you! I need a little time to verify things before merging.

**Comment by edvin** [comment]
Looks good, now I just need to figure out how to add private environment variables to the build environment :)

**Comment by edvin** [comment]
That was easy :) Very nice!

Setting environment variables from repository settings
$ export NEXUS_USERNAME=[secure]
$ export NEXUS_PASSWORD=[secure]

**Comment by edvin** [comment]
OK, it sort of worked. We also need to export variables for gpg signing, and changing making sure the signing step happens before deployment. I've manually changed sign-artifacts step from deploy to install before publishing releases. I've let it stay as `deploy` in the deployment descriptor so others building it locally wouldn't be required to sign. Any idea how we should handle this?

**Comment by abhinayagarwal** [comment]
For the signing part, we will have to either encrypt the `secret.gpg` and upload it to the repository. Or, we can save encode using BASE64 and save it as env variable. In [OpenJFX maven plugin](https://github.com/openjfx/javafx-maven-plugin/blob/master/.travis.yml), we use the former approach.

We also need to separate the deployment for snapshots and releases depending on what we want to achieve for each step.

**Pull request merged**
