### PR TITLE
Added convenience function builders for SimpleXXXProperty classes

### PR DESCRIPTION
**Pull request by LittleLightCz**

### CODE REVIEW

**Comment by edvin** [comment]
Very nice! Will you add a note to CHANGELOG as well?

**Comment by edvin** [comment]
Perhaps it would make sense to have an overload for listProperty which accepts varargs as well?

**Comment by edvin** [comment]
I'll do it :)

**Comment by LittleLightCz** [comment]
Ahh, sorry for the Changelog :grin: , but thank you :relaxed:

**Comment by edvin** [comment]
No problem, happy for every contribution :)

**Comment by LittleLightCz** [comment]
I am testing the latest snapshot version and there is one thing that hit my eye. For example now when I use `stringProperty("")`, then the inferred type is `SimpleStringProperty`. Therefore if I pass this val to some function, IDEA auto-generates parameter with `SimpleStringProperty` type as well, which pollutes the type name with the "Simple" word again :-)). So I was thinking, is it a good idea for the xxxProperty methods we've just added to return their parent class type instead? Could it cause any issues for some use-cases?

**Comment by edvin** [comment]
It's most definitely better if they return the parent class :)

**Comment by LittleLightCz** [comment]
Ok thanks for advice :-). I will do another PR and will try to fix it.

**Comment by edvin** [comment]
Great, thank you!

**Pull request merged**
